name: Release MariaDB 10.11 armv7l (cross)

on:
  workflow_dispatch:

env:
  IMAGE_TAR: mariadb-10-11-armv7l-${{ github.run_number }}.tar
  RELEASE_TAG: ${{ github.run_number }}
  CCACHE_DIR: /tmp/ccache

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # ---------- 源码 ----------
      - name: Checkout MariaDB 10.11
        uses: actions/checkout@v4
        with:
          repository: MariaDB/server
          ref: 10.11
          path: mariadb

      # ---------- 工具链 ----------
      - name: Install cross toolchain & 32-bit deps
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt-get update
          sudo apt-get install -y \
            gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
            cmake ninja-build pkg-config \
            libncurses5-dev:armhf libssl-dev:armhf \
            libzstd-dev:armhf libaio-dev:armhf \
            ccache

      # ---------- ccache ----------
      - name: ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-mariadb-10-11-armv7l-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-mariadb-10-11-armv7l-

      - name: Cross-compile
        run: |
          export CCACHE_DIR=${{ env.CCACHE_DIR }}
          export CC="ccache arm-linux-gnueabihf-gcc"
          export CXX="ccache arm-linux-gnueabihf-g++"
          mkdir build && cd build
          cmake ../mariadb \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=arm \
            -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
            -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr/local/mariadb \
            -DWITH_SSL=system \
            -DWITH_ZLIB=system \
            -DWITHOUT_TOKUDB=1 \
            -DWITHOUT_MROONGA=1 \
            -DWITHOUT_OQGRAPH=1 \
            -GNinja
          ninja -j$(nproc)
          DESTDIR=$PWD/install ninja install
          tar czf mariadb-install.tar.gz -C install .

      # ---------- 镜像打包 ----------
      - name: Generate image
        run: |
          mkdir stage
          tar xzf build/mariadb-install.tar.gz -C stage
          cat <<'EOF' > stage/Dockerfile
          FROM scratch
          COPY . /
          RUN ["/usr/local/mariadb/bin/mariadbd", "--version"]
          EOF
          docker buildx build --platform linux/arm/v7 \
            -t mariadb:10-11-armv7l-cross \
            --load stage
          docker save mariadb:10-11-armv7l-cross -o ${{ env.IMAGE_TAR }}

      # ---------- Release ----------
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "MariaDB 10.11 armv7l (cross) - ${{ github.event.repository.updated_at }}"
          files: ${{ env.IMAGE_TAR }}
          generate_release_notes: false
