name: Release MariaDB 10.11 armv7l (cross)

on:
  workflow_dispatch:

env:
  IMAGE_TAR: mariadb-10-11-armv7l-${{ github.run_number }}.tar
  RELEASE_TAG: ${{ github.run_number }}
  CROSS_ROOT: /opt/cross
  SYSROOT: /opt/cross/arm-linux-gnueabihf/libc

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install cross toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf \
                                  cmake ninja-build build-essential

      - name: Checkout MariaDB 10.11
        uses: actions/checkout@v4
        with:
          repository: MariaDB/server
          ref: 10.11
          path: mariadb

      - name: Cross-compile MariaDB
        run: |
          mkdir build && cd build
          cmake ../mariadb \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=arm \
            -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
            -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr/local/mariadb \
            -DWITH_SSL=system \
            -DWITH_ZLIB=system \
            -DWITHOUT_TOKUDB=1 \
            -DWITHOUT_MROONGA=1 \
            -DWITHOUT_OQGRAPH=1 \
            -GNinja
          ninja -j$(nproc)
          DESTDIR=$PWD/install ninja install
          tar czf mariadb-install.tar.gz -C install .

      - name: Generate Dockerfile & image
        run: |
          mkdir -p stage
          tar xzf build/mariadb-install.tar.gz -C stage
          cat <<'EOF' > stage/Dockerfile
          FROM scratch
          COPY . /
          RUN ["/usr/local/mariadb/bin/mariadbd", "--version"]
          EOF
          # 构建镜像（x86_64 runner 里直接打包）
          docker buildx build --platform linux/arm/v7 \
            -t mariadb:10-11-armv7l-cross \
            --load stage
          docker save mariadb:10-11-armv7l-cross -o ${{ env.IMAGE_TAR }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "MariaDB 10.11 armv7l (cross) - ${{ github.event.repository.updated_at }}"
          files: ${{ env.IMAGE_TAR }}
          generate_release_notes: false
