name: 为 ARM32 交叉编译 MariaDB

on:
  workflow_dispatch:  # 用户发起构建请求时触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出代码仓库

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1  # 设置QEMU以支持多架构
      with:
        platforms: arm

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # 设置Docker Buildx以支持多架构构建

    - name: Build Docker image
      uses: docker/build-push-action@v2  # 构建Docker镜像
      with:
        context: .
        file: ./Dockerfile  # 确保Dockerfile路径正确
        platforms: linux/arm/v7
        push: false  # 不推送到DockerHub
        load: true  # 将结果镜像加载到Docker中
        tags: mariadb:10.6-arm32  # 构建版本为MariaDB 10.6

    - name: Save Docker image to file
      run: docker save mariadb:10.6-arm32 -o mariadb-arm32.tar  # 保存Docker镜像到文件

    - name: Compress Docker image
      run: zip mariadb-arm32.zip mariadb-arm32.tar  # 压缩Docker镜像文件

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1  # 创建GitHub发行版
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: ${{ github.sha }}-$(date +'%Y%m%d%H%M%S')
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1  # 上传发行版资源
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mariadb-arm32.zip
        asset_name: mariadb-arm32.zip
        asset_content_type: application/zip
