name: 为 ARM32 交叉编译 MariaDB

on:
  workflow_dispatch:  # 用户发起构建请求时触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出代码仓库

    - name: Install cross-compilation tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake libssl-dev libncurses5-dev bison libaio-dev libboost-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev

    - name: Download MariaDB source code
      run: |
        wget https://downloads.mariadb.org/f/mariadb-10.6.5/source/mariadb-10.6.5.tar.gz
        tar -xzf mariadb-10.6.5.tar.gz
        cd mariadb-10.6.5

    - name: Build MariaDB
      run: |
        cd mariadb-10.6.5
        cmake . -DCMAKE_TOOLCHAIN_FILE=../toolchain-arm.cmake
        make -j$(nproc)

    - name: Compress build artifacts
      run: |
        tar -czf mariadb-arm32.tar.gz mariadb-10.6.5

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1  # 创建GitHub发行版
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: ${{ github.sha }}-$(date +'%Y%m%d%H%M%S')
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1  # 上传发行版资源
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mariadb-arm32.tar.gz
        asset_name: mariadb-arm32.tar.gz
        asset_content_type: application/gzip

