name: 为 ARM32 交叉编译 MariaDB

on:
  workflow_dispatch:  # 用户发起构建请求时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出代码仓库

    - name: Install cross-compilation tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf make
    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake libssl-dev libncurses5-dev bison libaio-dev libboost-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev
    - name: Download MariaDB source code
      run: |
        git clone https://github.com/MariaDB/server.git
        cd server
        git checkout 10.6
    - name: Set up cross-compilation environment
      run: |
        export CC=arm-linux-gnueabihf-gcc
        export CXX=arm-linux-gnueabihf-g++
        export AR=arm-linux-gnueabihf-ar
        export AS=arm-linux-gnueabihf-as
        export LD=arm-linux-gnueabihf-ld
        export NM=arm-linux-gnueabihf-nm
        export RANLIB=arm-linux-gnueabihf-ranlib
        export STRIP=arm-linux-gnueabihf-strip
    - name: Build MariaDB
      run: |
        cd server
        cmake .
        make -j$(nproc)
    - name: Compress build artifacts
      run: |
        tar -czf mariadb-arm32.tar.gz server
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.5.0
      with:
        name: mariadb-arm32
        path: mariadb-arm32.tar.gz

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: build-${{ github.run_id }}
        release_name: build-${{ github.run_id }}-$(date +'%Y%m%d%H%M%S')
        draft: false
        prerelease: false

    - name: Download build artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        name: mariadb-arm32
        path: .

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mariadb-arm32.tar.gz
        asset_name: mariadb-arm32.tar.gz
        asset_content_type: application/gzip

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: mariadb-arm32.tar.gz
        name: mariadb-arm32-${{ github.run_id }}
        tag_name: build-${{ github.run_id }}
        body: |
          构建产物: mariadb-arm32.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
